# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for building a standalone QSOCapture desktop EXE.

Build with:
    pyinstaller build.spec

The result is ``dist/QSOCapture.exe`` -- a single file that launches the
FastAPI server and opens the dashboard in an embedded WebView2 browser.
"""

import os

from PyInstaller.utils.hooks import collect_data_files, collect_dynamic_libs

# CEF (cefpython3) wheels are not published for every Python version (e.g.
# Python 3.10+ on Windows). We only bundle CEF when it is actually installed,
# so the build succeeds even when it is absent. The launcher treats CEF as an
# OPTIONAL backend (it prefers the always-available Edge WebView2 engine), so
# omitting it does not break the standalone window.
def _cef_binaries():
    try:
        import cefpython3  # noqa: F401
        return collect_dynamic_libs("cefpython3")
    except Exception:
        return []


def _cef_datas():
    try:
        import cefpython3  # noqa: F401
        return collect_data_files("cefpython3")
    except Exception:
        return []


block_cipher = None

# The dashboard HTML must be bundled so the launcher can copy it next to the
# executable on first run. The application icon (multi-size .ico generated by
# gen_icon.py from icon.svg) is bundled so the launcher can register it as the
# window icon and so main.py can serve it as the dashboard favicon.
datas = [
    ("index.html", "."),
    ("icon.ico", "."),
]

a = Analysis(
    ["launcher.py"],
    pathex=[os.getcwd()],
    binaries=_cef_binaries(),
    datas=datas + _cef_datas(),
    hiddenimports=[
        "main",
        "config",
        "db",
        "audio_manager",
        "n1mm_listener",
        "uvicorn.logging",
        "uvicorn.loops",
        "uvicorn.loops.auto",
        "uvicorn.protocols",
        "uvicorn.protocols.http",
        "uvicorn.protocols.http.auto",
        "uvicorn.protocols.websockets",
        "uvicorn.protocols.websockets.auto",
        "uvicorn.lifespan",
        "uvicorn.lifespan.on",
        "webview",
        # CEF (Chromium Embedded Framework) backend for pywebview. Ships a
        # full Chromium engine inside the package so the app opens in its own
        # window with no external WebView2/system-browser dependency.
        "cefpython3",
        "cefpython3.win",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name="QSOCapture",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,            # no console window for a desktop app
    disable_windowed_traceback=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon="icon.ico",
)
