# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for building a standalone QSOCapture desktop EXE.

Build with:
    pyinstaller build.spec

The result is ``dist/QSOCapture.exe`` -- a single file that launches the
FastAPI server and opens the dashboard in an embedded PySide6 QWebEngineView
browser (Qt WebEngine). Unlike the old pywebview-based build, this works on
all Windows versions (7+) with no external WebView2 or CEF dependency.
"""

import os

from PyInstaller.utils.hooks import collect_data_files, collect_dynamic_libs

block_cipher = None

# The dashboard HTML must be bundled so the launcher can copy it next to the
# executable on first run. The application icon (multi-size .ico generated by
# gen_icon.py from icon.svg) is bundled so the launcher can register it as the
# window icon and so main.py can serve it as the dashboard favicon.
datas = [
    ("index.html", "."),
    ("icon.svg", "."),
    ("icon.ico", "."),
]

a = Analysis(
    ["qt_launcher.py"],
    pathex=[os.getcwd()],
    binaries=[
        # QtWebEngineCore is a native DLL, not a pure Python module.
        # PyInstaller's hook for QtWebEngineWidgets should pick it up
        # automatically, but in some PySide6 versions it is missed.
        # We collect it explicitly to avoid ImportError at runtime.
        *collect_dynamic_libs("PySide6.QtWebEngineCore"),
    ],
    datas=datas,
    hiddenimports=[
        "main",
        "config",
        "db",
        "audio_manager",
        "n1mm_listener",
        "uvicorn.logging",
        "uvicorn.loops",
        "uvicorn.loops.auto",
        "uvicorn.protocols",
        "uvicorn.protocols.http",
        "uvicorn.protocols.http.auto",
        "uvicorn.protocols.websockets",
        "uvicorn.protocols.websockets.auto",
        "uvicorn.lifespan",
        "uvicorn.lifespan.on",
        # PySide6 (Qt for Python) with WebEngine for the embedded browser.
        "PySide6",
        "PySide6.QtCore",
        "PySide6.QtGui",
        "PySide6.QtWidgets",
        "PySide6.QtWebEngineWidgets",
        "PySide6.QtWebEngineCore",
        "PySide6.QtWebChannel",
        # shiboken6 is the CPython binding layer for PySide6; PyInstaller
        # sometimes misses it, so we list it explicitly.
        "shiboken6",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        # Qt modules we do NOT use — each can be 5-30 MB.
        # Only modules that are DEFINITELY not needed by QtWebEngine are excluded.
        # QtNetwork, QtXml, QtSvg, QtOpenGL, QtPositioning, QtQml, QtQuick,
        # QtWebSockets are kept because QtWebEngine may depend on them internally.
        "PySide6.QtBluetooth",
        "PySide6.Qt3DCore",
        "PySide6.Qt3DInput",
        "PySide6.Qt3DLogic",
        "PySide6.Qt3DRender",
        "PySide6.QtCharts",
        "PySide6.QtDataVisualization",
        "PySide6.QtDesigner",
        "PySide6.QtHelp",
        "PySide6.QtLocation",
        "PySide6.QtMultimedia",
        "PySide6.QtMultimediaWidgets",
        "PySide6.QtNfc",
        "PySide6.QtRemoteObjects",
        "PySide6.QtSensors",
        "PySide6.QtSerialPort",
        "PySide6.QtSql",
        "PySide6.QtTest",
        "PySide6.QtTextToSpeech",
        "PySide6.QtUiTools",
        # We use QWebEngineWidgets + QWebChannel, NOT QWebEngineQuick.
        "PySide6.QtWebEngineQuick",
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

# The EXE name carries the app version (when built via CI, APP_VERSION is
# exported from the git tag). Example:
#   QSOCapture-portable-0.5.0beta.exe
_APP_VERSION = os.environ.get("APP_VERSION", "")
_VER = ("-" + _APP_VERSION) if _APP_VERSION else ""
_EXE_NAME = f"QSOCapture-portable{_VER}"

# ── onedir build ──────────────────────────────────────────────────────────────
# The EXE itself (without binaries/zipfiles/datas — those go into COLLECT).
# This produces a folder instead of a single-file EXE, which eliminates the
# long startup delay caused by PyInstaller extracting everything to %TEMP%.
# The EXE is named "QSOCapture.exe" (no version suffix) so that the Inno Setup
# installer and shortcuts always point to a stable filename. The version is
# carried only in the parent folder name (set via COLLECT name=).
exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name="QSOCapture",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,            # no console window for a desktop app
    disable_windowed_traceback=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon="icon.ico",
)

# COLLECT gathers all the supporting files (DLLs, Python libs, Qt resources)
# into the same output directory, producing a fully self-contained folder.
# The folder name carries the version (e.g. QSOCapture-portable-0.5.0beta/).
coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name=_EXE_NAME,
)
